name: Test package

on: push

jobs:
  test:
    name: Run linter & test cases
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Poetry
        uses: Gr1N/setup-poetry@v8

      - name: Install dependencies
        run: poetry install --with test

      - name: Run linter
        run: poetry run ruff --format=github ctflib tests

      - name: Run tests
        run: poetry run pytest
